system:
  current_task: red
  save_root: ./saved_images
  show_window: false
colors:
  yellow:
    lower:
    - 66
    - 45
    - 153
    upper:
    - 90
    - 255
    - 255
    save_folder: yellow_results
    draw_color:
    - 0
    - 0
    - 255
  red:
    lower1:
    - 0
    - 43
    - 46
    upper1:
    - 10
    - 255
    - 255
    lower2:
    - 118
    - 68
    - 71
    upper2:
    - 158
    - 136
    - 240
    save_folder: red_results
    draw_color:
    - 0
    - 255
    - 0
